a:
	gcc A.c -o clientA
	./clientA

b:
	gcc B.c -o clientB
	./clientB

c:
	gcc C.c -o clientC -lsqlite3
	./clientC
d:
	gcc D.c -o clientD -lsqlite3
	./clientD
e:
	gcc E.c -o clientE -lsqlite3 -Wno-coverage-mismatch
	./clientE
f:
	gcc F.c -o clientF -lsqlite3
	./clientF
