clean:
	rm -rf *.o
p1:
	gcc p1_fork.c -o p1.o
	./p1.o
p2:
	gcc p2_forkNchild.c -o p2.o
	./p2.o
f1:
	gcc fifo1.c -o f1.o
	./f1.o
f2:
	gcc fifo2.c -o f2.o
	./f2.o
s1:
	gcc shm1.c -o s1.o
	./s1.o
s2:
	gcc shm2.c -o s2.o
	./s2.o
