
P1_hello:
	javac P1_hello.java
	java P1_hello

P2_print:
	javac P2_print.java
	java P2_print

P3_comment:
	javac P3_comment.java
	java P3_comment

P4_variables:
	javac P4_variables.java
	java P4_variables
