
P1_hello:
	javac P1_hello.java
	java P1_hello

P2_print:
	javac P2_print.java
	java P2_print

P3_comment:
	javac P3_comment.java
	java P3_comment

P4_variables:
	javac P4_variables.java
	java P4_variables

P5_typecast:
	javac P5_typecast.java
	java P5_typecast

P6_operators:
	javac P6_operators.java
	java P6_operators

P7_string:
	javac P7_string.java
	java P7_string

P8_math:
	javac P8_math.java
	java P8_math

P9_ifelse:
	javac P9_ifelse.java
	java P9_ifelse

P10_ternery:
	javac P10_ternery.java
	java P10_ternery

P11_switch:
	javac P11_switch.java
	java P11_switch

P12_loops:
	javac P12_loops.java
	java P12_loops

P13_array:
	javac P13_array.java
	java P13_array

P14_method:
	javac P14_method.java
	java P14_method

P15_overloading:
	javac P15_overloading.java
	java P15_overloading

P16_recursion:
	javac P16_recursion.java
	java P16_recursion

P17_object:
	javac P17_object.java
	java P17_object
